version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependency-cache-{{ checksum "yarn.lock" }}
          - v1-dependency-cache-
    - run: yarn install
    - save_cache:
        key: v1-dependency-cache-{{ checksum "yarn.lock" }}
        paths:
          - node_modules
    - run: yarn test
    - run: yarn lint
